name: Trigger auto deployment for sample-pka-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/sample-pka-container-app-AutoDeployTrigger-baa09ee5-62c7-4549-9de0-817964556876.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca413f596ddcacr.azurecr.io
          username: ${{ secrets.SAMPLEPKACONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SAMPLEPKACONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca413f596ddcacr.azurecr.io/sample-pka-container-app:${{ github.sha }}
          file: src/Dockerfile
          context: src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLEPKACONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sample-pka-container-app -g piotrkarpala_rg_5768 --server ca413f596ddcacr.azurecr.io --username  ${{ secrets.SAMPLEPKACONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.SAMPLEPKACONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n sample-pka-container-app -g piotrkarpala_rg_5768 --image ca413f596ddcacr.azurecr.io/sample-pka-container-app:${{ github.sha }}
